replicaCount: 3

image:
  repository: miky97/flask-aws-monitor
  tag: "2"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 5001

ingress:
  enabled: true
  hosts:
    - host: flask-monitor.prd.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
